require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PointsController do

  # This should return the minimal set of attributes required to create a valid
  # Point. As you add validations to Point, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PointsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all points as @points" do
      point = Point.create! valid_attributes
      get :index, {}, valid_session
      assigns(:points).should eq([point])
    end
  end

  describe "GET show" do
    it "assigns the requested point as @point" do
      point = Point.create! valid_attributes
      get :show, {:id => point.to_param}, valid_session
      assigns(:point).should eq(point)
    end
  end

  describe "GET new" do
    it "assigns a new point as @point" do
      get :new, {}, valid_session
      assigns(:point).should be_a_new(Point)
    end
  end

  describe "GET edit" do
    it "assigns the requested point as @point" do
      point = Point.create! valid_attributes
      get :edit, {:id => point.to_param}, valid_session
      assigns(:point).should eq(point)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Point" do
        expect {
          post :create, {:point => valid_attributes}, valid_session
        }.to change(Point, :count).by(1)
      end

      it "assigns a newly created point as @point" do
        post :create, {:point => valid_attributes}, valid_session
        assigns(:point).should be_a(Point)
        assigns(:point).should be_persisted
      end

      it "redirects to the created point" do
        post :create, {:point => valid_attributes}, valid_session
        response.should redirect_to(Point.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved point as @point" do
        # Trigger the behavior that occurs when invalid params are submitted
        Point.any_instance.stub(:save).and_return(false)
        post :create, {:point => { "name" => "invalid value" }}, valid_session
        assigns(:point).should be_a_new(Point)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Point.any_instance.stub(:save).and_return(false)
        post :create, {:point => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested point" do
        point = Point.create! valid_attributes
        # Assuming there are no other points in the database, this
        # specifies that the Point created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Point.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => point.to_param, :point => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested point as @point" do
        point = Point.create! valid_attributes
        put :update, {:id => point.to_param, :point => valid_attributes}, valid_session
        assigns(:point).should eq(point)
      end

      it "redirects to the point" do
        point = Point.create! valid_attributes
        put :update, {:id => point.to_param, :point => valid_attributes}, valid_session
        response.should redirect_to(point)
      end
    end

    describe "with invalid params" do
      it "assigns the point as @point" do
        point = Point.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Point.any_instance.stub(:save).and_return(false)
        put :update, {:id => point.to_param, :point => { "name" => "invalid value" }}, valid_session
        assigns(:point).should eq(point)
      end

      it "re-renders the 'edit' template" do
        point = Point.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Point.any_instance.stub(:save).and_return(false)
        put :update, {:id => point.to_param, :point => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested point" do
      point = Point.create! valid_attributes
      expect {
        delete :destroy, {:id => point.to_param}, valid_session
      }.to change(Point, :count).by(-1)
    end

    it "redirects to the points list" do
      point = Point.create! valid_attributes
      delete :destroy, {:id => point.to_param}, valid_session
      response.should redirect_to(points_url)
    end
  end

end
